"""Frozen eddy viscosity turbulence model for Re > ~5000.

Loads a pre-computed eddy viscosity field μ_t(x,y) from an external RANS solve
(OpenFOAM, k-ω SST, etc.) and uses it as a non-differentiable constant in the
SIMPLE momentum equation with effective viscosity μ_eff = μ + μ_t.

Gradients flow through geometry/BC parameters but NOT through μ_t. Valid for
small design perturbations; perturbation bound should be documented.

Validation gate: duct flow at Re=10000, Nusselt number within 15% of
Dittus-Boelter correlation.
"""

from __future__ import annotations

import torch
from torch import Tensor


class FrozenEddyViscosity:
    """Frozen eddy viscosity loader and interpolator.

    μ_t is treated as a non-differentiable constant tensor. SIMPLE autograd
    flows through μ_eff = μ + μ_t as usual.

    Args:
        mu_t: Eddy viscosity field (ny, nx), detached. Can be loaded from:
            - numpy array (from OpenFOAM postProcessing)
            - torch tensor (from external RANS solver)
            - generated by a simple mixing-length model
    """

    def __init__(self, mu_t: Tensor) -> None:
        self.mu_t = mu_t.detach()

    @classmethod
    def from_tensor(cls, mu_t: Tensor) -> "FrozenEddyViscosity":
        """Create from an existing tensor (will be detached)."""
        return cls(mu_t)

    @classmethod
    def from_numpy(cls, mu_t_array, device: str = "cpu") -> "FrozenEddyViscosity":
        """Create from a numpy array."""
        import numpy as np
        if isinstance(mu_t_array, np.ndarray):
            mu_t = torch.tensor(mu_t_array, dtype=torch.float32, device=device)
        else:
            mu_t = torch.tensor(float(mu_t_array), dtype=torch.float32, device=device)
        return cls(mu_t)

    @classmethod
    def mixing_length_model(
        cls,
        ny: int,
        nx: int,
        ly: float,
        kappa: float = 0.41,
        device: str = "cpu",
    ) -> "FrozenEddyViscosity":
        """Generate μ_t using the mixing-length model for a 2D channel.

        Uses van Driest damped mixing length with an assumed law-of-the-wall
        velocity profile. Requires u_tau estimate — use from_blasius() for automatic
        friction velocity calculation from bulk Reynolds number.
        """
        import warnings
        warnings.warn(
            "mixing_length_model() requires u_tau; use mixing_length_channel() or "
            "from_blasius() instead.",
            DeprecationWarning, stacklevel=2,
        )
        return cls(torch.zeros(ny, nx, dtype=torch.float32, device=device))

    @classmethod
    def from_blasius(
        cls,
        Re: float,
        ny: int,
        nx: int,
        ly: float,
        U_bulk: float = 1.0,
        kappa: float = 0.41,
        device: str = "cpu",
    ) -> "FrozenEddyViscosity":
        """Create mixing-length eddy viscosity with Blasius friction velocity.

        Uses the Blasius correlation for turbulent pipe/channel flow:
            f = 0.316 * Re^(-0.25)   (valid for Re ∈ [4000, 100000])
            u_tau = U_bulk * sqrt(f/2)

        Args:
            Re: Bulk Reynolds number U·L/ν.
            ny, nx: Grid dimensions.
            ly: Channel height.
            U_bulk: Bulk (mean) velocity.
            kappa: von Kármán constant (0.41).
            device: PyTorch device.
        """
        import math
        f = 0.316 * Re ** (-0.25)
        u_tau = U_bulk * math.sqrt(f / 2)
        nu = U_bulk * ly / Re
        return cls.mixing_length_channel(
            ny=ny, nx=nx, ly=ly, u_tau=u_tau, nu=nu,
            kappa=kappa, device=device,
        )

    @classmethod
    def mixing_length_channel(
        cls,
        ny: int,
        nx: int,
        ly: float,
        u_tau: float,
        nu: float,
        kappa: float = 0.41,
        device: str = "cpu",
    ) -> "FrozenEddyViscosity":
        """Generate μ_t for a fully-developed turbulent channel using mixing length.

        Uses the van Driest damped mixing length:
            l_mix = κ * y * [1 - exp(-y⁺/A⁺)]  where A⁺ = 26

        Combined with the law-of-the-wall velocity gradient:
            du/dy = u_tau / (κ * y)  for y⁺ > 11
            du/dy = u_tau² / ν       for y⁺ ≤ 11 (viscous sublayer)

        μ_t = l_mix² * |du/dy|

        Args:
            ny, nx: Grid dimensions.
            ly: Channel height.
            u_tau: Friction velocity.
            nu: Kinematic viscosity.
            kappa: von Kármán constant (0.41).
            device: PyTorch device.
        """
        dy = ly / ny
        _y_plus_max = u_tau * ly / (2 * nu)

        # Cell center positions (distance from nearest wall)
        y = torch.arange(ny, dtype=torch.float32, device=device) * dy + dy / 2
        y_wall = torch.minimum(y, ly - y)  # distance from nearest wall

        y_plus = u_tau * y_wall / nu

        # Van Driest damped mixing length
        A_plus = 26.0
        l_mix = kappa * y_wall * (1.0 - torch.exp(-y_plus / A_plus))

        # Velocity gradient from law of the wall
        du_dy = torch.where(
            y_plus > 11.0,
            u_tau / (kappa * y_wall + 1e-10),
            torch.tensor(u_tau ** 2 / nu, dtype=torch.float32, device=device),
        )

        # Eddy viscosity: μ_t = l_mix² * |du/dy|
        mu_t_1d = l_mix ** 2 * du_dy.abs()

        # Broadcast to 2D (uniform in x for fully-developed channel)
        mu_t = mu_t_1d.unsqueeze(1).expand(ny, nx)

        return cls(mu_t)

    def effective_viscosity(self, mu: float) -> Tensor:
        """Compute effective viscosity μ_eff = μ + μ_t.

        Args:
            mu: Molecular (laminar) kinematic viscosity.

        Returns:
            μ_eff tensor (ny, nx).
        """
        return self.mu_t + mu

    def effective_thermal_diffusivity(
        self, alpha: float, Pr_t: float = 0.9
    ) -> Tensor:
        """Compute effective thermal diffusivity α_eff = α + μ_t / Pr_t.

        Turbulent Prandtl number Pr_t ≈ 0.9 is standard for wall-bounded flows.

        Args:
            alpha: Molecular thermal diffusivity k/(ρ·cp).
            Pr_t: Turbulent Prandtl number (default 0.9).

        Returns:
            α_eff tensor (ny, nx).
        """
        return alpha + self.mu_t / Pr_t

    def perturbation_validity_check(
        self,
        mu_t_new: Tensor,
        cosine_threshold: float = 0.9,
    ) -> float:
        """Check if a new μ_t field is close enough to the frozen one.

        Computes cosine similarity between flattened μ_t fields. Returns
        the cosine similarity value (should be > cosine_threshold).

        This validates the frozen μ_t assumption for design perturbations.
        """
        v1 = self.mu_t.flatten()
        v2 = mu_t_new.detach().flatten()
        cos_sim = torch.dot(v1, v2) / (v1.norm() * v2.norm() + 1e-10)
        return cos_sim.item()
