"""Neural surrogate for the SIMPLE CFD solver.

Adapted from DiffNano's NeuralSurrogate pattern.  Trains a lightweight CNN
(_FieldNet) to predict [ux, uy, p] fields from a design density field, using
ground-truth data generated by NavierStokes2D.solve_steady.

MAC grid layout (for reference):
  ux : (ny,   nx+1)  x-velocity on vertical faces
  uy : (ny+1, nx  )  y-velocity on horizontal faces
  p  : (ny,   nx  )  pressure at cell centres

The CNN predicts all three fields on the *pressure grid* (ny, nx) for
simplicity.  During training, MAC velocities are interpolated to cell centres
to form the regression target.

Usage
-----
>>> from diffcfd.solvers.navier_stokes_2d import NavierStokes2D
>>> from diffcfd.surrogates.simple_surrogate import SimpleSurrogate
>>> solver = NavierStokes2D(reynolds_number=100, grid=(32, 16))
>>> surr = SimpleSurrogate(solver)
>>> surr.train_surrogate(n_samples=20, n_epochs=30)
>>> ux, uy, p = surr.predict(design)
"""

from __future__ import annotations

import torch
import torch.nn as nn
from torch import Tensor

from diff_surrogate import CorrectionPolicy
from diff_surrogate.base import SurrogateStats

__all__ = ["SimpleSurrogate"]


# ---------------------------------------------------------------------------
# _FieldNet — lightweight CNN for field prediction
# ---------------------------------------------------------------------------


class _FieldNet(nn.Module):
    """CNN that maps a density field to predicted [ux, uy, p] fields.

    Architecture: 4 conv layers with ReLU activations and zero-padding to
    preserve spatial dimensions (no pooling).

    Parameters
    ----------
    hidden_channels : int
        Number of channels in hidden conv layers.
    """

    def __init__(self, hidden_channels: int = 32) -> None:
        super().__init__()
        self.encoder = nn.Sequential(
            # Layer 1: (B, 1, H, W) -> (B, hidden_channels, H, W)
            nn.Conv2d(1, hidden_channels, kernel_size=3, padding=1),
            nn.ReLU(inplace=True),
            # Layer 2: (B, hidden_channels, H, W) -> (B, hidden_channels, H, W)
            nn.Conv2d(hidden_channels, hidden_channels, kernel_size=3, padding=1),
            nn.ReLU(inplace=True),
            # Layer 3: (B, hidden_channels, H, W) -> (B, hidden_channels, H, W)
            nn.Conv2d(hidden_channels, hidden_channels, kernel_size=3, padding=1),
            nn.ReLU(inplace=True),
            # Layer 4: (B, hidden_channels, H, W) -> (B, 3, H, W)
            nn.Conv2d(hidden_channels, 3, kernel_size=3, padding=1),
        )

    def forward(self, x: Tensor) -> Tensor:
        """Forward pass.

        Parameters
        ----------
        x : Tensor
            Design density field of shape (B, 1, H, W) with values in [0, 1].

        Returns
        -------
        Tensor
            Predicted [ux, uy, p] fields of shape (B, 3, H, W).
        """
        return self.encoder(x)


# ---------------------------------------------------------------------------
# SimpleSurrogate — training + prediction wrapper
# ---------------------------------------------------------------------------


class SimpleSurrogate:
    """Neural surrogate that accelerates the SIMPLE CFD solver.

    Trains _FieldNet on (design, flow-field) pairs generated by the full
    NavierStokes2D solver, then provides fast forward passes during
    optimisation.  Periodically corrects with a full-solver call governed
    by a ``CorrectionPolicy`` from the diff-surrogate package.

    Parameters
    ----------
    base_solver : NavierStokes2D
        The underlying SIMPLE solver used for training data generation and
        periodic correction.
    hidden_channels : int
        Width of hidden conv layers in _FieldNet.
    correction_interval : int
        Run full SIMPLE solve every N-th ``predict`` call for correction.
        Set to 0 or negative to disable periodic correction.
    lr : float
        Learning rate for Adam optimiser during surrogate training.
    device : str or torch.device
        Device for tensors and the neural network.
    """

    def __init__(
        self,
        base_solver,
        hidden_channels: int = 32,
        correction_interval: int = 10,
        lr: float = 1e-3,
        device: str | torch.device = "cpu",
    ) -> None:
        self.base_solver = base_solver
        self._device = torch.device(device)
        self.correction_interval = correction_interval

        self._correction_policy = CorrectionPolicy(
            correction_interval=correction_interval,
        )
        self._forward_count = 0
        self._stats = SurrogateStats()

        self.net = _FieldNet(hidden_channels=hidden_channels).to(self._device).float()
        self.optimizer = torch.optim.Adam(self.net.parameters(), lr=lr)
        self._trained = False

    # ------------------------------------------------------------------
    # Public helpers
    # ------------------------------------------------------------------

    @property
    def device(self) -> torch.device:
        return self._device

    @staticmethod
    def _mac_to_cell_centre(
        ux: Tensor,
        uy: Tensor,
        ny: int,
        nx: int,
    ) -> tuple[Tensor, Tensor]:
        """Interpolate MAC velocities to cell-centre (ny, nx) grid.

        Parameters
        ----------
        ux : Tensor
            x-velocity on vertical faces, shape (ny, nx+1).
        uy : Tensor
            y-velocity on horizontal faces, shape (ny+1, nx).
        ny, nx : int
            Cell counts.

        Returns
        -------
        ux_cc, uy_cc : Tensor, Tensor
            Cell-centred velocities, each shape (ny, nx).
        """
        # Average left/right face values at each cell
        ux_cc = 0.5 * (ux[:, :-1] + ux[:, 1:])  # (ny, nx)
        # Average bottom/top face values at each cell
        uy_cc = 0.5 * (uy[:-1, :] + uy[1:, :])  # (ny, nx)
        return ux_cc, uy_cc

    # ------------------------------------------------------------------
    # Training
    # ------------------------------------------------------------------

    def train_surrogate(
        self,
        n_samples: int = 200,
        n_epochs: int = 50,
        threshold: float = 0.5,
        batch_size: int | None = None,
        inlet_velocity: float = 1.0,
        case: str = "channel",
        verbose: bool = True,
    ) -> list[float]:
        """Train the surrogate on synthetic data from the base solver.

        Generates random density fields, runs the full SIMPLE solver to obtain
        ground-truth (ux, uy, p), interpolates to cell-centre grid, and trains
        _FieldNet with MSE loss.

        Parameters
        ----------
        n_samples : int
            Number of random design samples to generate.
        n_epochs : int
            Number of training epochs.
        threshold : float
            Binarisation threshold for converting random density to solid/fluid.
            Values below threshold become solid (1 in the design mask).
        batch_size : int or None
            Mini-batch size.  Defaults to ``min(32, n_samples)``.
        inlet_velocity : float
            Inlet velocity used for all training solves.
        case : str
            Flow case passed to ``solve_steady`` (e.g. "channel", "cavity").
        verbose : bool
            Print training progress every 10 epochs.

        Returns
        -------
        loss_history : list[float]
            Mean loss per epoch.
        """
        self.net.train()

        ny, nx = self.base_solver.ny, self.base_solver.nx

        # ----- Generate training data -----
        designs: list[Tensor] = []
        targets: list[Tensor] = []

        for i in range(n_samples):
            # Random density field on pressure grid, values in [0, 1]
            raw = torch.rand(ny, nx, dtype=torch.float32, device=self._device)
            # Binarise: values < threshold become solid (1), else fluid (0)
            design = (raw < threshold).float()

            with torch.no_grad():
                # Use the raw density field as the SDF-like input so the solver
                # generates a Brinkman penalisation field internally.
                # Positive sdf = fluid, negative = solid, so we negate the mask
                # so that design=1 (solid) yields negative sdf.
                sdf = -(2.0 * design - 1.0)  # +1 fluid, -1 solid

                ux, uy, p = self.base_solver.solve_steady(
                    sdf=sdf,
                    inlet_velocity=inlet_velocity,
                    case=case,
                )

            # Interpolate MAC velocities to cell centres on (ny, nx) grid
            ux_cc, uy_cc = self._mac_to_cell_centre(ux, uy, ny, nx)

            # Stack into target: (3, ny, nx)
            target = torch.stack([ux_cc, uy_cc, p], dim=0).float()

            designs.append(design)
            targets.append(target)

            if verbose and (i + 1) % 50 == 0:
                print(f"  Generated {i + 1}/{n_samples} training samples")

        # (n_samples, 1, ny, nx) — single input channel
        X = torch.stack(designs).unsqueeze(1)
        # (n_samples, 3, ny, nx)
        Y = torch.stack(targets)

        # ----- Training loop -----
        if batch_size is None:
            batch_size = min(32, n_samples)

        loss_history: list[float] = []

        for epoch in range(n_epochs):
            perm = torch.randperm(n_samples, device=self._device)
            epoch_loss = 0.0
            n_batches = 0

            for start in range(0, n_samples, batch_size):
                idx = perm[start : start + batch_size]
                batch_x = X[idx]
                batch_y = Y[idx]

                pred = self.net(batch_x)
                loss = nn.functional.mse_loss(pred, batch_y)

                self.optimizer.zero_grad()
                loss.backward()
                self.optimizer.step()

                epoch_loss += loss.item()
                n_batches += 1

            avg_loss = epoch_loss / max(1, n_batches)
            loss_history.append(avg_loss)

            if verbose and (epoch % 10 == 0 or epoch == n_epochs - 1):
                print(f"Epoch {epoch:4d}/{n_epochs}: loss={avg_loss:.6f}")

        self._trained = True
        self.net.eval()
        return loss_history

    # ------------------------------------------------------------------
    # Prediction
    # ------------------------------------------------------------------

    def predict(
        self,
        design: Tensor,
        inlet_velocity: float = 1.0,
        case: str = "channel",
    ) -> tuple[Tensor, Tensor, Tensor]:
        """Predict flow fields from a design density field.

        Uses the trained CNN for fast prediction.  Every ``correction_interval``
        calls (if positive), falls back to the full SIMPLE solver.

        Parameters
        ----------
        design : Tensor
            Design density field of shape (ny, nx) or (1, ny, nx) with values
            in [0, 1] (sigmoid output).
        inlet_velocity : float
            Inlet velocity (used only for full-solver correction calls).
        case : str
            Flow case (used only for full-solver correction calls).

        Returns
        -------
        ux_cc, uy_cc, p : Tensor, Tensor, Tensor
            Predicted cell-centred velocity components and pressure, each on
            the (ny, nx) pressure grid.
        """
        self._forward_count += 1
        self._stats.total_predictions += 1

        # Periodic full-solver correction via CorrectionPolicy
        if not self._trained or self._correction_policy.should_correct(
            self._forward_count
        ):
            self._stats.total_corrections += 1
            return self._full_solve(design, inlet_velocity, case)

        # Ensure design is 4D: (1, 1, ny, nx)
        x = design.float().to(self._device)
        if x.dim() == 2:
            x = x.unsqueeze(0).unsqueeze(0)
        elif x.dim() == 3:
            x = x.unsqueeze(1)

        with torch.no_grad():
            pred = self.net(x)  # (1, 3, ny, nx)

        ux_cc = pred[0, 0]  # (ny, nx)
        uy_cc = pred[0, 1]
        p = pred[0, 2]

        return ux_cc, uy_cc, p

    def _full_solve(
        self,
        design: Tensor,
        inlet_velocity: float,
        case: str,
    ) -> tuple[Tensor, Tensor, Tensor]:
        """Run the full SIMPLE solver and interpolate to cell centres."""
        design_f = design.float().to(self._device)
        if design_f.dim() > 2:
            design_f = design_f.squeeze(0)

        sdf = -(2.0 * design_f - 1.0)
        ny, nx = self.base_solver.ny, self.base_solver.nx

        with torch.no_grad():
            ux, uy, p = self.base_solver.solve_steady(
                sdf=sdf,
                inlet_velocity=inlet_velocity,
                case=case,
            )

        ux_cc, uy_cc = self._mac_to_cell_centre(ux, uy, ny, nx)
        return ux_cc, uy_cc, p

    # ------------------------------------------------------------------
    # Accuracy evaluation
    # ------------------------------------------------------------------

    def accuracy(
        self,
        n_test: int = 50,
        threshold: float = 0.5,
        inlet_velocity: float = 1.0,
        case: str = "channel",
    ) -> dict[str, float]:
        """Evaluate surrogate accuracy against the base solver.

        Parameters
        ----------
        n_test : int
            Number of test samples.
        threshold : float
            Binarisation threshold for random density fields.
        inlet_velocity : float
            Inlet velocity for test solves.
        case : str
            Flow case for test solves.

        Returns
        -------
        metrics : dict[str, float]
            ``mean_max_rel_error`` and ``worst_max_rel_error`` across test set.
        """
        self.net.eval()
        ny, nx = self.base_solver.ny, self.base_solver.nx
        errors: list[float] = []

        for _ in range(n_test):
            raw = torch.rand(ny, nx, dtype=torch.float32, device=self._device)
            design = (raw < threshold).float()
            sdf = -(2.0 * design - 1.0)

            with torch.no_grad():
                ux, uy, p = self.base_solver.solve_steady(
                    sdf=sdf,
                    inlet_velocity=inlet_velocity,
                    case=case,
                )
                ux_cc, uy_cc = self._mac_to_cell_centre(ux, uy, ny, nx)
                exact = torch.stack([ux_cc, uy_cc, p], dim=0).unsqueeze(0)

                approx = self.net(design.unsqueeze(0).unsqueeze(1))

            rel_err = (exact - approx).abs() / (exact.abs() + 1e-8)
            errors.append(rel_err.max().item())

        return {
            "mean_max_rel_error": sum(errors) / len(errors),
            "worst_max_rel_error": max(errors),
        }
